const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const fmt=n=>Math.floor(n).toLocaleString("ar-IQ");
const GOODS=[["خبز","🥖",12,5],["حليب","🥛",18,8],["شيبس","🍟",25,11],["عصير","🧃",32,14],["ماء","💧",15,6],["رز","🍚",40,19]];
const KEY="grocery-tycoon-v1";
export class Game{constructor(c){this.c=c;this.x=c.getContext("2d");this.p={x:0,y:0};this.j={x:0,y:0};this.money=500;this.level=1;this.xp=0;this.sales=0;this.staff=0;this.exp=0;this.fridges=0;this.station=false;this.customers=[];this.floaters=[];this.load();this.bind();this.resize()}
load(){try{Object.assign(this,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{}this.spawn(6)}save(){localStorage.setItem(KEY,JSON.stringify({money:this.money,level:this.level,xp:this.xp,sales:this.sales,staff:this.staff,exp:this.exp,fridges:this.fridges,station:this.station}))}
resize(){const r=this.c.getBoundingClientRect();this.d=Math.min(devicePixelRatio||1,2);this.w=r.width;this.h=r.height;this.c.width=this.w*this.d;this.c.height=this.h*this.d;this.x.setTransform(this.d,0,0,this.d,0,0)}
bind(){addEventListener("resize",()=>this.resize());const j=document.getElementById("joystick"),k=document.getElementById("stick");let on=0;const mv=e=>{if(!on)return;const r=j.getBoundingClientRect(),p=e.touches?e.touches[0]:e,dx=p.clientX-r.left-r.width/2,dy=p.clientY-r.top-r.height/2,m=44,q=Math.min(m,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);this.j.x=Math.cos(a)*q/m;this.j.y=Math.sin(a)*q/m;k.style.transform=`translate(${this.j.x*30}px,${this.j.y*30}px)`};const end=()=>{on=0;this.j.x=this.j.y=0;k.style.transform=""};j.ontouchstart=e=>{on=1;mv(e)};j.ontouchmove=e=>{e.preventDefault();mv(e)};j.ontouchend=end;j.ontouchcancel=end;document.getElementById("action").onclick=()=>this.interact();document.getElementById("pause").onclick=()=>{this.pause=!this.pause;document.getElementById("pause").textContent=this.pause?"▶":"Ⅱ"};document.getElementById("closePanel").onclick=()=>document.getElementById("panel").classList.add("hidden");document.getElementById("shopBtn").onclick=()=>this.panel("shop");document.getElementById("staffBtn").onclick=()=>this.panel("staff");document.getElementById("expandBtn").onclick=()=>this.panel("expand")}
start(){this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}loop(t){const dt=Math.min(.035,(t-this.last)/1000);this.last=t;if(!this.pause)this.update(dt);this.draw(t);requestAnimationFrame(q=>this.loop(q))}
update(dt){this.p.x=clamp(this.p.x+this.j.x*3*dt,-4.5,4.5);this.p.y=clamp(this.p.y+this.j.y*3*dt,-3.6,3.6);for(const q of this.customers){q.x+=Math.cos(q.a)*q.s*dt;q.y+=Math.sin(q.a)*q.s*dt;if(Math.abs(q.x)>4.6||Math.abs(q.y)>3.7)q.a+=Math.PI;if(Math.random()<dt*.025)this.customerSale(q)}this.floaters.forEach(f=>{f.life-=dt;f.y-=dt*.3});this.floaters=this.floaters.filter(f=>f.life>0);this.near=this.nearest();this.xp+=this.staff*.12*dt;this.levelUp();this.saveTimer=(this.saveTimer||0)+dt;if(this.saveTimer>5){this.save();this.saveTimer=0}this.hud()}
spawn(n){for(let i=0;i<n;i++)this.customers.push({x:(Math.random()-.5)*7,y:(Math.random()-.5)*5,a:Math.random()*6.28,s:.15+Math.random()*.22,h:Math.random()*4})}nearest(){const a=[["cash",2.5,-2.1,"الكاشير"],["stock",-2.2,-1.2,"المخزن"],["door",0,3.2,"الباب"]];let z=null,d=1.1;for(const q of a){const dd=Math.hypot(this.p.x-q[1],this.p.y-q[2]);if(dd<d){d=dd;z=q}}return z}
interact(){if(!this.near){this.toast("اقترب من نقطة التفاعل");return}if(this.near[0]==="cash")this.sell();else if(this.near[0]==="stock")this.panel("shop");else this.toast("الزبائن ينتظرونك 👋")}
sell(){const g=GOODS[this.sales%GOODS.length],v=g[2];this.money+=v;this.sales++;this.xp+=8;this.floaters.push({x:this.p.x,y:this.p.y,life:1,text:"+"+v+" د.ع"});this.toast("بيعة ناجحة: "+g[0]+" +"+v+" د.ع")}
customerSale(q){if(this.staff<1&&Math.random()<.55)return;const g=GOODS[Math.floor(Math.random()*GOODS.length)];this.money+=g[2];this.sales++;this.xp+=3;this.floaters.push({x:q.x,y:q.y,life:.7,text:"+"+g[2]})}
levelUp(){const need=this.level*100;if(this.xp>=need){this.xp-=need;this.level++;this.money+=this.level*100;const e=document.getElementById("levelUp");document.getElementById("levelTitle").textContent="مستوى "+this.level+"!";document.getElementById("levelText").textContent="مكافأة "+fmt(this.level*100)+" د.ع";e.classList.remove("hidden");setTimeout(()=>e.classList.add("hidden"),1600)}}

panel(type){const b=document.getElementById("panelBody");b.textContent="";const title=document.createElement("h2");title.textContent=type==="shop"?"🛍️ البضاعة":type==="staff"?"👥 الموظفون":"🏗️ التوسعة";b.append(title);const p=document.createElement("p");p.textContent=type==="shop"?"اشترِ مخزونًا وارفع تنوع المتجر.":type==="staff"?"الموظفون يجعلون المتجر يعمل حتى بدونك.":"كبّر البقالة حتى تصل إلى محطة الوقود.";b.append(p);if(type==="shop")GOODS.forEach(g=>this.item(b,g[1]+" "+g[0],"مخزون • سعر البيع "+g[2],Math.max(50,g[3]*10),()=>this.toast("تم تجهيز "+g[0])));if(type==="staff")this.item(b,"🧑 موظف مبيعات","يزيد المبيعات التلقائية",500+this.staff*350,()=>{this.money-=500+this.staff*350;this.staff++;this.spawn(2);this.save()});if(type==="expand"){this.item(b,"🗄️ رف إضافي","يزيد قدرة المتجر",300+this.exp*200,()=>{this.money-=300+this.exp*200;this.exp++;this.save()});this.item(b,"🧊 ثلاجة عرض","تجذب زبائن أكثر",1200+this.fridges*900,()=>{this.money-=1200+this.fridges*900;this.fridges++;this.spawn(3);this.save()});if(this.level>=8)this.item(b,"⛽ محطة وقود","المرحلة الكبرى",50000,()=>{this.money-=50000;this.station=true;this.toast("افتتحت محطة الوقود!");this.save()})}document.getElementById("panel").classList.remove("hidden")}
item(root,name,desc,cost,fn){const d=document.createElement("div");d.className="item";d.innerHTML=`<span>${name}</span><small>${desc}</small><button class="buy">${fmt(cost)} د.ع</button>`;const btn=d.querySelector("button");btn.disabled=this.money<cost;btn.onclick=()=>{if(this.money>=cost){fn();this.panel(document.querySelector("#panel h2").textContent.includes("الموظفون")?"staff":document.querySelector("#panel h2").textContent.includes("التوسعة")?"expand":"shop")}};root.append(d)}
toast(s){const e=document.getElementById("toast");e.textContent=s;e.style.opacity=1;clearTimeout(this.tt);this.tt=setTimeout(()=>e.style.opacity=0,1300)}hud(){document.getElementById("money").textContent=fmt(this.money);document.getElementById("objectiveTitle").textContent=this.station?"بقالة + محطة وقود":"مستوى المتجر "+this.level;document.getElementById("objectiveText").textContent="خبرة "+fmt(this.xp)+" / "+fmt(this.level*100)+" • المبيعات "+fmt(this.sales);const h=document.getElementById("hint");h.classList.toggle("show",!!this.near);h.textContent=this.near?"تفاعل: "+this.near[3]:""}
world(wx,wy){const s=Math.min(this.w,this.h)*.075;return[this.w/2+(wx-wy)*s,this.h*.53+(wx+wy)*s*.5]}
tile(x,y,fill){const p=this.world(x,y),s=Math.min(this.w,this.h)*.075;this.x.beginPath();this.x.moveTo(p[0],p[1]-s*.5);this.x.lineTo(p[0]+s,p[1]);this.x.lineTo(p[0],p[1]+s*.5);this.x.lineTo(p[0]-s,p[1]);this.x.closePath();this.x.fillStyle=fill;this.x.fill();this.x.strokeStyle="#fff7";this.x.stroke()}
draw(t){const x=this.x;x.clearRect(0,0,this.w,this.h);const sky=x.createLinearGradient(0,0,0,this.h);sky.addColorStop(0,"#bde5e2");sky.addColorStop(1,"#f7f0d9");x.fillStyle=sky;x.fillRect(0,0,this.w,this.h);for(let y=-5;y<6;y++)for(let z=-6;z<7;z++)this.tile(z,y,(z+y)%2?"#b7d89e":"#c6e2ac");this.drawStore(t);for(const q of this.customers)this.person(q.x,q.y,q.h,t);this.person(this.p.x,this.p.y,5,t);x.font="800 12px Cairo";x.textAlign="center";for(const f of this.floaters){const p=this.world(f.x,f.y);x.globalAlpha=clamp(f.life,0,1);x.fillStyle="#17755d";x.fillText(f.text,p[0],p[1]-30*(1-f.life))}x.globalAlpha=1}
drawStore(t){const s=Math.min(this.w,this.h)*.075;this.tile(0,0,"#f3d29f");const c=this.world(0,0),x=this.x;x.fillStyle="#e57854";x.fillRect(c[0]-s*2.6,c[1]-s*1.3,s*5.2,s*.5);x.fillStyle="#fff8e5";x.font="900 "+Math.max(13,s*.28)+"px Cairo";x.textAlign="center";x.fillText(this.station?"بقالتي 24H":"بقالتي",c[0],c[1]-s*.95);for(let i=0;i<3+this.exp;i++){const p=this.world(-2+i*.9,-.4);x.fillStyle="#997454";x.fillRect(p[0]-s*.2,p[1]-s*.08,s*.4,s*.16)}const q=this.world(2.5,-2);x.fillStyle="#4f8c72";x.fillRect(q[0]-s*.3,q[1]-s*.15,s*.6,s*.3);if(this.fridges)for(let i=0;i<this.fridges;i++){const z=this.world(-1+i*.8,1.5);x.fillStyle="#aee1eb";x.fillRect(z[0]-s*.18,z[1]-s*.25,s*.36,s*.45)}if(this.station){const z=this.world(3.5,1.4);x.fillStyle="#f3f0e6";x.fillRect(z[0]-s*.6,z[1]-s*.4,s*1.2,s*.7);x.fillStyle="#e95c4b";x.fillRect(z[0]-s*.6,z[1]-s*.4,s*1.2,s*.13);x.fillStyle="#fff";x.font="900 "+s*.2+"px Cairo";x.fillText("⛽",z[0],z[1])}}
person(wx,wy,h,t){const p=this.world(wx,wy),s=Math.min(this.w,this.h)*.075,b=Math.sin(t/240+h)*2,x=p[0],y=p[1]+b,X=this.x;X.fillStyle="#37554e33";X.beginPath();X.ellipse(x,y+s*.25,s*.22,s*.08,0,0,6.28);X.fill();X.fillStyle=["#6685b5","#dc8568","#70a47d","#9a78ad"][h%4|0];X.beginPath();X.roundRect(x-s*.16,y-s*.05,s*.32,s*.38,s*.07);X.fill();X.fillStyle="#efc7a8";X.beginPath();X.arc(x,y-s*.18,s*.14,0,6.28);X.fill();X.fillStyle="#45545a";X.fillRect(x-s*.11,y+s*.32,s*.07,s*.18);X.fillRect(x+s*.04,y+s*.32,s*.07,s*.18)}
}