const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const fmt=n=>Math.floor(n).toLocaleString("ar-IQ");
const GOODS=[["خبز","🥖",12,5],["حليب","🥛",18,8],["شيبس","🍟",25,11],["عصير","🧃",32,14],["ماء","💧",15,6],["رز","🍚",40,19]];
const KEY="grocery-tycoon-v1";
export class Game{constructor(c){this.c=c;this.x=c.getContext("2d");this.p={x:0,y:0};this.j={x:0,y:0};this.money=500;this.level=1;this.xp=0;this.sales=0;this.staff=0;this.exp=0;this.fridges=0;this.station=false;this.customers=[];this.floaters=[];this.load();this.bind();this.resize()}
load(){try{Object.assign(this,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{}this.spawn(6)}save(){localStorage.setItem(KEY,JSON.stringify({money:this.money,level:this.level,xp:this.xp,sales:this.sales,staff:this.staff,exp:this.exp,fridges:this.fridges,station:this.station}))}
resize(){const r=this.c.getBoundingClientRect();this.d=Math.min(devicePixelRatio||1,2);this.w=r.width;this.h=r.height;this.c.width=this.w*this.d;this.c.height=this.h*this.d;this.x.setTransform(this.d,0,0,this.d,0,0)}
bind(){addEventListener("resize",()=>this.resize());const j=document.getElementById("joystick"),k=document.getElementById("stick");let on=0;const mv=e=>{if(!on)return;const r=j.getBoundingClientRect(),p=e.touches?e.touches[0]:e,dx=p.clientX-r.left-r.width/2,dy=p.clientY-r.top-r.height/2,m=44,q=Math.min(m,Math.hypot(dx,dy)),a=Math.atan2(dy,dx);this.j.x=Math.cos(a)*q/m;this.j.y=Math.sin(a)*q/m;k.style.transform=`translate(${this.j.x*30}px,${this.j.y*30}px)`};const end=()=>{on=0;this.j.x=this.j.y=0;k.style.transform=""};j.ontouchstart=e=>{on=1;mv(e)};j.ontouchmove=e=>{e.preventDefault();mv(e)};j.ontouchend=end;j.ontouchcancel=end;document.getElementById("action").onclick=()=>this.interact();document.getElementById("pause").onclick=()=>{this.pause=!this.pause;document.getElementById("pause").textContent=this.pause?"▶":"Ⅱ"};document.getElementById("closePanel").onclick=()=>document.getElementById("panel").classList.add("hidden");document.getElementById("shopBtn").onclick=()=>this.panel("shop");document.getElementById("staffBtn").onclick=()=>this.panel("staff");document.getElementById("expandBtn").onclick=()=>this.panel("expand")}
start(){this.last=performance.now();requestAnimationFrame(t=>this.loop(t))}loop(t){const dt=Math.min(.035,(t-this.last)/1000);this.last=t;if(!this.pause)this.update(dt);this.draw(t);requestAnimationFrame(q=>this.loop(q))}
update(dt){this.p.x=clamp(this.p.x+this.j.x*3*dt,-4.5,4.5);this.p.y=clamp(this.p.y+this.j.y*3*dt,-3.6,3.6);for(const q of this.customers){q.x+=Math.cos(q.a)*q.s*dt;q.y+=Math.sin(q.a)*q.s*dt;if(Math.abs(q.x)>4.6||Math.abs(q.y)>3.7)q.a+=Math.PI;if(Math.random()<dt*.025)this.customerSale(q)}this.floaters.forEach(f=>{f.life-=dt;f.y-=dt*.3});this.floaters=this.floaters.filter(f=>f.life>0);this.near=this.nearest();this.xp+=this.staff*.12*dt;this.levelUp();this.saveTimer=(this.saveTimer||0)+dt;if(this.saveTimer>5){this.save();this.saveTimer=0}this.hud()}
spawn(n){for(let i=0;i<n;i++)this.customers.push({x:(Math.random()-.5)*7,y:(Math.random()-.5)*5,a:Math.random()*6.28,s:.15+Math.random()*.22,h:Math.random()*4})}nearest(){const a=[["cash",2.5,-2.1,"الكاشير"],["stock",-2.2,-1.2,"المخزن"],["door",0,3.2,"الباب"]];let z=null,d=1.1;for(const q of a){const dd=Math.hypot(this.p.x-q[1],this.p.y-q[2]);if(dd<d){d=dd;z=q}}return z}
interact(){if(!this.near){this.toast("اقترب من نقطة التفاعل");return}if(this.near[0]==="cash")this.sell();else if(this.near[0]==="stock")this.panel("shop");else this.toast("الزبائن ينتظرونك 👋")}
sell(){const g=GOODS[this.sales%GOODS.length],v=g[2];this.money+=v;this.sales++;this.xp+=8;this.floaters.push({x:this.p.x,y:this.p.y,life:1,text:"+"+v+" د.ع"});this.toast("بيعة ناجحة: "+g[0]+" +"+v+" د.ع")}
customerSale(q){if(this.staff<1&&Math.random()<.55)return;const g=GOODS[Math.floor(Math.random()*GOODS.length)];this.money+=g[2];this.sales++;this.xp+=3;this.floaters.push({x:q.x,y:q.y,life:.7,text:"+"+g[2]})}
levelUp(){const need=this.level*100;if(this.xp>=need){this.xp-=need;this.level++;this.money+=this.level*100;const e=document.getElementById("levelUp");document.getElementById("levelTitle").textContent="مستوى "+this.level+"!";document.getElementById("levelText").textContent="مكافأة "+fmt(this.level*100)+" د.ع";e.classList.remove("hidden");setTimeout(()=>e.classList.add("hidden"),1600)}}
